// This file acts as a template for local development. 
// Copy it to config.js and add your local credentials if needed.
// In Vercel production, config.js is automatically generated by build.js
window.ENV = {
    SUPABASE_URL: "LOCAL_DEV_REPLACE_ME",
    SUPABASE_ANON_KEY: "LOCAL_DEV_REPLACE_ME"
};
