// This file acts as a template for local development.
// Copy it to config.js and add your local credentials if needed.
// In Vercel production, config.js is automatically generated by build.js
//
// Expected shape matches build.js output (see also .env.example).
// Example project URL: https://zfpqdsdawjjwsxtfbgjf.supabase.co
window.ENV = {
    SUPABASE_URL: "LOCAL_DEV_REPLACE_ME",
    SUPABASE_PUBLIC_KEY: "LOCAL_DEV_REPLACE_ME",
    SUPABASE_ANON_KEY: "LOCAL_DEV_REPLACE_ME",
    AUTH_REDIRECT_URL: "http://localhost:3000/"
};
